Helper generator for export options
bitrise-io/go-xcode pull request #128
Opened 2021-11-08 14:02 UTC by shams-ahmed

Helper methods for generating export options

2021-11-09 10:00 UTC, lpusok requested changes

2021-11-09 10:05 UTC, lpusok commented on exportOptionsGenerator/exportOptionsGenerator.go
> +func NewExportOptionsGenerator(xcodeProj *xcodeproj.XcodeProj, scheme *xcscheme.Scheme, configuration string, logger log.Logger) ExportOptionsGenerator {
The existing code only supports **xcodeproj.XcodeProj* , to be able to use this from the **export-xcarchive** Step you need to introduce something like *NewXcarchiveGenerator*.

2021-11-09 11:51 UTC, shams-ahmed commented on exportOptionsGenerator/exportOptionsGenerator.go
> +func NewExportOptionsGenerator(xcodeProj *xcodeproj.XcodeProj, scheme *xcscheme.Scheme, configuration string, logger log.Logger) ExportOptionsGenerator {
Updated constructor name to `new`

2021-11-15 12:22 UTC, godrei approved these changes

2021-11-15 12:22 UTC, godrei commented on exportoptionsgenerator/exportoptionsgenerator.go
> +		// Propably due to App store IPAs containing App Clips also, which are executable targets with a separate bundle ID.
NOTE: typo `Propably` -> `Probably`

2021-11-15 16:19 UTC, lpusok approved these changes

2021-11-15 16:41 UTC, merged