added testFlightInternalTestingOnly appStore option
bitrise-io/go-xcode pull request #257
Opened 2024-12-27 04:07 UTC by naveen-bitrise

Export Options now supports a `testFlightInternalTestingOnly` boolean option for app-store distribution method. 

This pull request adds that option to v1

2025-01-07 08:29 UTC, godrei commented on bitrise.yml
> -format_version: 1.0.0
The project's CI setup has been changed recently this change pulls the bitrise.yml from the master branch.

2025-01-07 08:39 UTC, godrei requested changes

2025-01-07 08:39 UTC, godrei commented on exportoptions/appstore_options.go
> +	// TestFlightInternalTestingOnly
This comment is unnecessary, please remove it.

2025-01-07 08:39 UTC, godrei commented on exportoptions/appstore_options.go
> +	if options.TestFlightInternalTestingOnly {
For the other boolean export options, we only set the given option if it has a non-default value (see `UploadBitcode` for example).
For the sake of consistency, I suggest following this pattern (constant for the default value of testFlightInternalTestingOnly [false] + only setting the option if the value is non-default).

2025-01-07 08:44 UTC, godrei commented
I also suggest extending the unit test to cover the new changes:
- TestNewAppStoreOptions -> should verify if the constructor creates export options with TestFlightInternalTestingOnly = false
- TestAppStoreOptionsToHash -> should verify if TestFlightInternalTestingOnly = true in the generated hash the expected key and value presents

2025-01-08 23:17 UTC, naveen-bitrise commented on exportoptions/appstore_options.go
> +	if options.TestFlightInternalTestingOnly {
Hi @godrei,

When I used `if options.TestFlightInternalTestingOnly != TestFlightInternalTestingOnlyDefault`, I got the following linting error

```
exportoptions/appstore_options.go:79:5: S1002: should omit comparison to bool constant, can be simplified to `options.TestFlightInternalTestingOnly` (gosimple)
	if options.TestFlightInternalTestingOnly != TestFlightInternalTestingOnlyDefault {
	   ^
S1002: should omit comparison to bool constant, can be simplified to `options.TestFlightInternalTestingOnly
```

I got to a green build by commenting that off and used just `if options.TestFlightInternalTestingOnly`, let me know what I should do here.

2025-01-09 09:24 UTC, godrei commented on exportoptions/appstore_options.go
> +	if options.TestFlightInternalTestingOnly {
Hi @naveen-bitrise, I updated the code to use the `if options.TestFlightInternalTestingOnly != TestFlightInternalTestingOnlyDefault` if statement. The failing linter is silenced with a `//nolint:gosimple` directive similar to the other boolean options.

I think this supports better code consistency and also expresses more that we only write non-default options to the final .plist file.

2025-01-09 09:24 UTC, godrei approved these changes

2025-01-09 09:24 UTC, merged