Added testFlightInternalTestingOnly to GenerateApplicationExportOptions method
bitrise-io/go-xcode pull request #258
Opened 2024-12-27 04:12 UTC by naveen-bitrise

Added testFlightInternalTestingOnly to GenerateApplicationExportOptions method. 

GenerateApplicationExportOptions calls `addTestFlightInternalTestingOnly` method.

The go.mod files may not be needed, and may need to updated separately

2025-01-07 08:58 UTC, godrei requested changes

2025-01-07 08:58 UTC, godrei commented on exportoptionsgenerator/exportoptionsgenerator.go
> +	if testFlightInternalTestingOnly {
It seems this option was introduced in Xcode 15 (https://github.com/fastlane/fastlane/discussions/21525), I suggest setting this option only if xcodeMajorVersion >= 15 similarly to `addDistributionBundleIdentifierFromXcode12`.

2025-01-07 08:59 UTC, godrei commented
Please fix the existing tests and add at least one new test case (for the `TestExportOptionsGenerator_GenerateApplicationExportOptions_ForAutomaticSigningStyle`), which verifies that the new option appears in the generated export options.

2025-01-08 23:20 UTC, naveen-bitrise commented
@godrei I added the tests, however there are some merge conflicts. I am not sure how to resolve them as they have to do with dependencies. could you help?

2025-01-14 09:01 UTC, godrei approved these changes

2025-01-14 09:01 UTC, merged